import { z } from 'zod';

// Building blocks shared by the stored documents (docs/SPEC.md, Domain model).
// This package runs in the browser too: no node:* imports, Buffer or process.

// Every document _id is a random UUID generated by the api.
export const Id = z.uuid();
export type Id = z.infer<typeof Id>;

// Text with at least one visible character, for quotes and labels.
export const NonBlank = z.string().regex(/\S/, { error: 'must not be blank' });

// A US ticker (NVDA) or a home listing (2330.TW).
export const Ticker = z
  .string()
  .max(12)
  .regex(/^[A-Z0-9]+(?:[.-][A-Z0-9]+)*$/);
export type Ticker = z.infer<typeof Ticker>;

// Theme taxonomy, SPEC.md Interest graph.
export const THEMES = [
  'ai_accelerators',
  'cloud',
  'chip_design',
  'foundry',
  'semicap_equipment',
  'memory',
  'networking',
  'smartphones',
  'pc',
  'data_centers',
  'energy',
  'oil_gas',
  'consumer_staples',
  'pharma',
  'healthcare',
  'regulation',
  'trade_policy',
  'rates_macro',
  'cybersecurity',
  'autos_ev',
] as const;
export const Theme = z.enum(THEMES);
export type Theme = z.infer<typeof Theme>;

// Source tiers, SPEC.md: 1 primary, 2 wires, 3 social.
export const Tier = z.union([z.literal(1), z.literal(2), z.literal(3)]);
export type Tier = z.infer<typeof Tier>;

// Computed by code from source tier and corroboration.
export const Confidence = z.enum(['high', 'medium', 'low']);
export type Confidence = z.infer<typeof Confidence>;

// An LLM classification against the SPEC.md rubric: 1 routine to 5 major.
export const Importance = z.int().min(1).max(5);
export type Importance = z.infer<typeof Importance>;

// Computed by code from graph paths.
export const Relevance = z.number().min(0).max(1);
export type Relevance = z.infer<typeof Relevance>;

// Local Xenova/all-MiniLM-L6-v2, cosine (SPEC.md Stack).
export const EMBEDDING_DIMENSIONS = 384;
export const Embedding = z.array(z.number()).length(EMBEDDING_DIMENSIONS);
export type Embedding = z.infer<typeof Embedding>;

export const LlmProvider = z.enum(['groq', 'google']);
export type LlmProvider = z.infer<typeof LlmProvider>;
